on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - '27017:27017'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
      - run: |
          npm ci
          npm run test:cov
          npm run test:e2e
          npm run lint -- --max-warnings=0
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: Unit
          parallel: true
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: E2E
          path-to-lcov: ./coverage-e2e/lcov.info
          parallel: true
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: coverage
          path: coverage
